### ISSUE TITLE
windows 10 multi monitor, immediately crashes

### ISSUE THREAD

**Issue by dev-mciot** [KrasnovM/Gamma-Manager#10]
Program immediately closes without opening directly after start, no error messages or something just the tray in task info shows up for a few seconds

**Comment by Destined2** [comment]
same here on windows 10

**Comment by leah7-7** [comment]
you can go to windows event viewer and see what exactly causes the crash. (Event Viewer > Windows Logs > Application) in my case it was like this - fixed by enabling ddc/ci
in my monitor osd
`Application: Gamma Manager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException
   at System.Management.ManagementException.ThrowWithExtendedInfo(System.Management.ManagementStatus)
   at System.Management.ManagementObjectCollection+ManagementObjectEnumerator.MoveNext()
   at Gamma_Manager.InternalMonitor.GetBrightness()
   at Gamma_Manager.Display+<>cDisplayClass7_0.<QueryDisplayDevices>b0(IntPtr, IntPtr, RECT ByRef, IntPtr)`

**Comment by dev-mciot** [comment]
> you can go to windows event viewer and see what exactly causes the crash. (Event Viewer > Windows Logs > Application) in my case it was like this - fixed by enabling ddc/ci in my monitor osd `Application: Gamma Manager.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Management.ManagementException at System.Management.ManagementException.ThrowWithExtendedInfo(System.Management.ManagementStatus) at System.Management.ManagementObjectCollection+ManagementObjectEnumerator.MoveNext() at Gamma_Manager.InternalMonitor.GetBrightness() at Gamma_Manager.Display+<>cDisplayClass7_0.<QueryDisplayDevices>b0(IntPtr, IntPtr, RECT ByRef, IntPtr)`

same for me

**Comment by JaydenZJJ** [comment]
> you can go to windows event viewer and see what exactly causes the crash. (Event Viewer > Windows Logs > Application) in my case it was like this - fixed by enabling ddc/ci in my monitor osd `Application: Gamma Manager.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Management.ManagementException at System.Management.ManagementException.ThrowWithExtendedInfo(System.Management.ManagementStatus) at System.Management.ManagementObjectCollection+ManagementObjectEnumerator.MoveNext() at Gamma_Manager.InternalMonitor.GetBrightness() at Gamma_Manager.Display+<>cDisplayClass7_0.<QueryDisplayDevices>b0(IntPtr, IntPtr, RECT ByRef, IntPtr)`

Thank you, can confirm this fix works. I have dual display and one of them did not enable DDC/CI, after enabling it, the software launches normally.
